apps:
  - name: hello
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
  - name: hello2
    helmrelease:
      namespace: default
      chart: hello
      sourceRef:
        kind: HelmRepository
        name: hello
  - name: hello3
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
      values: |
          fullnameOverride: hello3-inlinevalue
  - name: hello4
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
      valuesFiles:
        - values/hello4.yaml
  - name: hello5
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
      values: |
        {{ .Files.Get "values/hello5.yaml" }}
  - name: nginx2
    gitrepository:
      url: https://github.com/taylorshaulis/flux-apps
      branch: main
    kustomization:
      namespace: default
      path: kustomize_example
      patches:
        - patch: |-
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: not-used
            spec:
              template:
                spec:
                  containers:
                    - name: nginx
                      image: nginx:1.21.0       
          target:
            kind: Deployment
            labelSelector: "app=nginx"