apps:
  - name: hello
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
  - name: hello2
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
  - name: hello3
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
      values: |
          fullnameOverride: helloolleh
          autoscaling:
            enabled: true
            minReplicas: 1
            maxReplicas: 3
            targetCPUUtilizationPercentage: 80