apps:
  hello:
    helmrelease:
      values: |
        fullnameOverride: hello
  hello2:
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
