global:
  fluxnamespace: flux-system
  helmrepository:
    interval: 1h
  helmrelease:
    interval: 1m
  gitrepository:
    interval: 1h
    branch: master
  kustomization:
    interval: 1m

apps:
  - name: hello
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
  - name: hello2
    helmrelease:
      namespace: default
      chart: hello
      sourceRef:
        kind: HelmRepository
        name: hello
  - name: hello3
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
      values: |
          fullnameOverride: hello3-example