global:
  fluxnamespace: flux-system
  helmrepository:
    interval: 1h
  helmrelease:
    interval: 1m
  gitrepository:
    interval: 1h
    branch: master
  kustomization:
    interval: 1m

apps:
  hello:
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
  hello2:
    helmrelease:
      namespace: default
      chart: hello
      sourceRef:
        kind: HelmRepository
        name: hello
