apps:
  - name: hello
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      namespace: default
      chart: hello
  - name: helloolleh
    helmrepository:
      url: https://cloudecho.github.io/charts/
    helmrelease:
      install:
        createnamespace: true
      namespace: helloolleh
      chart: hello
      values: |
        {{ .Files.Get "values/helloolleh.yaml" | nindent 2}}