apps:
  - name: echoserver
    gitrepository:
      url: https://github.com/taylorshaulis/chicken.git
      branch: main
    helmrelease:
      namespace: default
      chart: charts/echoserver

  - name: echohelm
    helmrepository:
      url: https://github.com/taylorshaulis/chicken.git
    helmrelease:
      namespace: default
      chart: charts/echoserver
      version: "1.4"
      values: |
        parameters:
          - name: clusterName
            value: my-cluster

  - name: echoexists
    helmrelease:
      namespace: default
      chart: charts/echoserver
      version: "1.4"
    sourceRef:
      kind: HelmRepository
      name: echohelm

  - name: aws-load-balancer
    helmrepository:
      url: https://aws.github.io/eks-charts
    helmrelease:
      namespace: kube-system
      chart: aws-load-balancer-controller
      version: "1.4.4"
      values: |
        parameters:
          - name: clusterName
            value: my-cluster

  - name: ingress-nginx
    helmrepository:
      url: https://kubernetes.github.io/ingress-nginx
    helmrelease:
      namespace: kube-system
      chart: ingress-nginx
      version: "4.1.2"
      values: |
        {{ .Files.Get "ingress_nginx.values.yaml" | nindent 2}}