{{ range $name, $app := .Values.apps }}
{{- if .gitrepository }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.fluxnamespace }}
spec:
  {{- if .gitrepository.interval }}
  interval: {{ .gitrepository.interval }}
  {{- else }}
  interval: {{ $.Values.global.gitrepository.interval }}
  {{- end }}
  url:  {{ .gitrepository.url }}
  ref:
    {{- if .gitrepository.branch }}
    branch: {{ .gitrepository.branch }}
    {{- else }}
    branch: {{ $.Values.global.gitrepository.branch }}
    {{- end }}
---
{{- end }}
{{- if .helmrepository }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.fluxnamespace }}
spec:
  {{- if .helmrepository.interval }}
  interval: {{ .helmrepository.interval }}
  {{- else }}
  interval: {{ $.Values.global.helmrepository.interval }}
  {{- end }}
  url: {{ .helmrepository.url }}
---
{{- end }}
{{- if .helmrelease }}
{{- range .helmrelease.valuesFiles }}
{{- $valuesname := . |  trimAll ".yaml" | replace "/" "-"}}
{{- $valuesfile := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $valuesname }}-values-configmap
  namespace: {{ $.Values.global.fluxnamespace }}
data:
  values.yaml: |-
{{ $.Files.Get $valuesfile | indent 4}}
---
{{- end }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.fluxnamespace }}
spec:
  {{- if .helmrelease.targetNamespace }}
  targetNamespace: {{ .helmrelease.targetNamespace }}
  {{- else }}
  targetNamespace: {{ .helmrelease.namespace }}
  {{- end }}
  {{- if .helmrelease.storageNamespace }}
  storageNamespace: {{ .helmrelease.storageNamespace }}
  {{- end }}
  {{- if .helmrelease.maxHistory }}
  maxHistory: {{ .helmrelease.maxHistory }}
  {{- end }}
  {{- if .helmrelease.serviceAccountName }}
  serviceAccountName: {{ .helmrelease.serviceAccountName }}
  {{- end }}
  {{- if .helmrelease.interval }}
  interval: {{ .helmrelease.interval }}
  {{- else }}
  interval: {{ $.Values.global.helmrelease.interval }}
  {{- end }}
  {{- if .helmrelease.install }}
  install:
    {{- if .helmrelease.install.createnamespace }}}
    createNamespace: true
    {{- end}}
    {{- if .helmrelease.install.replace }}}
    replace: {{ .helmrelease.install.replace }}
    {{- end}}
  {{- end }}
  {{- if .helmrelease.suspend }}
  suspend: {{ .helmrelease.suspend }}
  {{- end }}
  {{- if .helmrelease.releaseName }}
  releaseName: {{ .helmrelease.releaseName }}
  {{- end }}
  chart:
    spec:
      chart: {{ .helmrelease.chart }}
      {{- if .helmrelease.version }}
      version: {{ .helmrelease.version }}
      {{- end }}
      reconcileStrategy: Revision
      sourceRef:
        {{- if .gitrepository }}
        kind: GitRepository
        name: {{ $name }}
        {{- else if .helmrepository  }}
        kind: HelmRepository
        name: {{ $name }}
        {{- else }}
        kind: {{ .helmrelease.sourceRef.kind }}
        name: {{ .helmrelease.sourceRef.name }}
        {{- end}}
      {{- if .helmrelease.interval }}
      interval: {{ .helmrelease.interval }}
      {{- else }}
      interval: {{ $.Values.global.helmrelease.interval }}
      {{- end }}
  {{- if .helmrelease.valuesFiles }}
  valuesFrom:
  {{- range .helmrelease.valuesFiles }}
  {{- $valuesname := . |  trimAll ".yaml" | replace "/" "-"}}
  - kind: ConfigMap
    name: {{ $valuesname }}-values-configmap
  {{- end }}
  {{- end }}
  {{- if .helmrelease.values }}
  values:
  {{- tpl .helmrelease.values $ | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .kustomization }}
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.fluxnamespace }}
spec:
  {{- if .kustomization.interval }}
  interval: {{ .kustomization.interval }}
  {{- else }}
  interval: {{ $.Values.global.kustomization.interval }}
  {{- end }}
  prune: true
  targetNamespace: {{ .kustomization.namespace }}
  sourceRef:
    {{- if .gitrepository }}
    kind: GitRepository
    name: {{ $name }}
    {{- else if .helmrepository  }}
    kind: HelmRepository
    name: {{ $name }}
    {{- else }}
    kind: {{ .sourceRef.kind }}
    name: {{ .sourceRef.name }}
    {{- end}}
  path: {{ .kustomization.path }}
  {{- if .kustomization.patches }}
  patches:
  {{- range .kustomization.patches }}
    - patch: |-
{{ .patch | indent 8}}
      target:
        {{- if .target.kind }}
        kind: {{ .target.kind }}
        {{- end}}
        {{- if .target.labelSelector }}
        labelSelector: {{ .target.labelSelector | quote }}
        {{- end}}
        {{- if .target.name }}
        name: {{ .target.name }}
        {{- end}}
        {{- if .target.namespace }}
        namespace: {{ .target.namespace }}
        {{- end}}
  {{- end}}
  {{- end}}
---
{{- end }}
{{ end }}